[project]
name = "confocal"
version = "0.1.2"
description = "Multi-layer configuration management with source tracking"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "Your Name", email = "your.email@example.com"},
]
dependencies = [
    "pydantic>=2.0.0,<2.9.0",
    "pydantic-settings>=2.0.0,<2.9.0",
    "rich>=13.0.0",
]
[project.optional-dependencies]
dev = [
    "build>=0.10.0",
    "twine>=4.0.0",
    "pytest>=7.0.0",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true


[project.urls]
Homepage = "https://github.com/joshuafcole/confocal"
Repository = "https://github.com/joshuafcole/confocal"

[tool.hatch.build.targets.wheel]
packages = ["src/confocal"]

[tool.hatch.build.targets.sdist]
only-include = ["src"]
